CREATE TABLE IF NOT EXISTS player_profiles (
    user_id UUID PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    level INT NOT NULL DEFAULT 1,
    exp INT NOT NULL DEFAULT 0,
    gold INT NOT NULL DEFAULT 0,
    gems INT NOT NULL DEFAULT 0,
    stamina INT NOT NULL DEFAULT 120,
    max_stamina INT NOT NULL DEFAULT 120,
    mmr INT NOT NULL DEFAULT 1000,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
